# Generated by Django 4.1.4 on 2022-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='New note', max_length=240)),
                ('emoji', models.CharField(help_text='🔥', max_length=1)),
                ('creation', models.DateTimeField(help_text='Created on')),
            ],
        ),
    ]
