# Generated by Django 4.1.4 on 2022-12-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, help_text='Created on'),
        ),
    ]
