# Generated by Django 4.1.4 on 2022-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='body',
            field=models.TextField(default='', help_text='Text of your note'),
        ),
    ]
