# Generated by Django 4.1.4 on 2022-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_note_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(default='', help_text='Text of your note', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='emoji',
            field=models.CharField(help_text='Emoji', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='New note', max_length=240, null=True),
        ),
    ]
